# Generated by Django 2.0.2 on 2018-12-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apistep',
            name='apiresponse',
            field=models.CharField(max_length=5000, null=True, verbose_name='响应数据'),
        ),
        migrations.AddField(
            model_name='apistep',
            name='apistep',
            field=models.CharField(max_length=100, null=True, verbose_name='测试步聚'),
        ),
    ]
